apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpr-app
  labels:
    app: vpro-app
spec:
  selector:
    matchLabels:
      app: vpro-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: vpro-app
    spec:
      containers:
        - name: {{ .Values.app.containername }}
          image: {{ .Values.app.image }}
          imagePullPolicy: {{ .Values.app.imagePolicy }}
          ports:
            - containerPort: {{ .Values.app.servicePort }}
              name: vproapp-port
      initContainers:
        - name:  init-mydb
          image: busybox
          command: ['sh', '-c',"until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"] 
        - name:  init-memcached
          image: busybox
          command: ['sh', '-c',"until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"] 


    

