apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vpro-app
  ports:
    - port: {{ .values.app.servicePort }}
      targetPort: {{ .values.app.servicePort }}
      protocol: TCP
  type: LoadBalancer
