apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    ginx.ingress.kubernetes.io/rewrite-target: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: prefix
          backend:
            service:
              name: vproapp-service
              port: 
                number: {{ .values.app.servicePort }}
                
                
