apiVersion: v1 
kind: Service
metadata:
  name: vprocache01
  labels:
    app: vpro-mc
spec:
  selector:
    app: vpro-mc
  ports:
    - port: {{ .Values.memcached.servicePort }}
      targetPort: {{ .Values.memcached.servicePort }}
      protocol: TCP
  type: ClusterIP
