apiVersion: v1
kind: Service
metadata:
  name: vprodb
  labels:
    app: vpro-db
spec:
  selector:
    app: vpro-db
  ports:
    - port: {{ .Values.mysql.servicePort }}
      targetPort: {{ .Values.mysql.servicePort }}
      protocol: TCP
  type: ClusterIP
