apiVersion: v1
kind: Service
metadata:
  name: vprodb
  labels:
    app: vpro-db
spec:
  selector:
    app: vpro-
  ports:
    - port: 3306
      targetPort: vprodb-port
      protocol: TCP
  type: ClusterIP
