apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vpro-db
spec:
  selector:
    matchLabels:
      app: vpro-db
  replicas: 1 
  template:
    metadata:
      labels:
        app: vpro-db
    spec:
      containers:
        - name: {{ .Values.mysql.containername }}
          image: {{ .Values.mysql.image }}
          volumeMounts:
            - mountPath: {{ .Values.mysql.mountPath }}
              name: vpro-db-data
          ports:
            - containerPort: {{ .Values.mysql.servicePort }}
              name: vprodb-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.secretname }}
                  key: {{ .Values.mysql.secretkey }}
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: mysql-pvc
      initContainers:
        - name: busybox
          image: busybox
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - mountPath: {{ .Values.mysql.mountPath }}
              name: vpro-db-data