apiVersion: v1
kind: Deployment
metadata:
  name: vpromq
  labels:
    app: vpro-mq
spec:
  selector:
    matchLabels:
      app: vpro-mq
  replicas: 1 
  template:
    metadata:
      name: vpromq
      labels:
        app: vpro-mq
    spec:
      containers:
      - image:  {{ .Values.rabbitmq.image }}
        name:  {{ .Values.rabbitmq.containername }}
        ports:
          - containerPort: {{ .Values.rabbitmq.servicePort }}
            name: vpromq-port
        env:
        - name:  RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.secretname }}
              key: {{ .Values.rabbitmq.secretkey }}
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.user }}