apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  labels:
    app: vpro-mq
spec:
  selector:
    app: vpro-mq
  ports:
    - port: {{ .Values.rabbitmq.servicePort }}
      targetPort: {{ .Values.rabbitmq.servicePort }}
      protocol: TCP
  type: ClusterIP
