app:
  servicePort: 8080
  image: 845087560966.dkr.ecr.ap-south-1.amazonaws.com/cicd-project-app
  containername: vpro-app
  imagePolicy: Always
 
mysql:
  servicePort: 3306
  image: 0845087560966.dkr.ecr.ap-south-1.amazonaws.com/cicd-project-db
  mountPath: /var/lib/mysql
  password: vprodbpass
  secretname: mysecret
  containername: vprodb
  secretname: mysecret
  secretkey: db-pass

rabbitmq:
  password: guest
  servicePort: 5672
  containername: vpromq
  image: rabbitmq
  user: guest
  secretname: mysecret
  secretkey: rmq-pass

memcached:
  containername: vprodb
  image: memcached
  servicePort: 11211

ingress:
  host: 
